apiVersion: v1
kind: Namespace
metadata:
  name: core
  annotations:
    "helm.sh/resource-policy": keep
    "app.kubernetes.io/managed-by": "Helm"
    "linkerd.io/inject" : enabled
    # "config.linkerd.io/trace-collector": collector.linkerd-jaeger:14268

---

apiVersion: v1
kind: Namespace
metadata:
  name:  orchestrator
  annotations:
    "helm.sh/resource-policy": keep
    "linkerd.io/inject" : enabled
    "config.linkerd.io/trace-collector": collector.linkerd-jaeger:55678 # or 14268?


---

apiVersion: v1
kind: Secret
metadata:
  name: rabbit
  namespace: orchestrator
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc | quote }}

---

apiVersion: v1
kind: Namespace
metadata:
  name: uva
  annotations:
    "helm.sh/resource-policy": keep
    "app.kubernetes.io/managed-by": "Helm"
    "config.linkerd.io/trace-collector": collector.linkerd-jaeger:55678 # or 14268?

---

apiVersion: v1
kind: Secret
metadata:
  name: rabbit
  namespace: uva
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc | quote }}

---

apiVersion: v1
kind: Namespace
metadata:
  name: vu
  annotations:
    "helm.sh/resource-policy": keep
    "app.kubernetes.io/managed-by": "Helm"
    "config.linkerd.io/trace-collector": collector.linkerd-jaeger:55678 # or 14268?


---

apiVersion: v1
kind: Secret
metadata:
  name: rabbit
  namespace: vu
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc | quote }}

---

apiVersion: v1
kind: Namespace
metadata:
  name: surf
  annotations:
    "helm.sh/resource-policy": keep
    "app.kubernetes.io/managed-by": "Helm"
    "linkerd.io/inject" : disabled
    "config.linkerd.io/trace-collector": collector.linkerd-jaeger:55678 # or 14268?

---

apiVersion: v1
kind: Secret
metadata:
  name: rabbit
  namespace: surf
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc | quote }}

---

apiVersion: v1
kind: Namespace
metadata:
  name:  ingress
  annotations:
    "helm.sh/resource-policy": keep
    # "linkerd.io/inject" : enabled
    # "config.linkerd.io/trace-collector": collector.linkerd-jaeger:55678 # or 14268?

---

apiVersion: v1
kind: Secret
metadata:
  name: rabbit
  namespace: ingress
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc | quote }}

---

apiVersion: v1
kind: Namespace
metadata:
  name:  api-gateway
  annotations:
    "helm.sh/resource-policy": keep
    "linkerd.io/inject" : enabled
    "config.linkerd.io/trace-collector": collector.linkerd-jaeger:55678 # or 14268?

---

apiVersion: v1
kind: Secret
metadata:
  name: rabbit
  namespace: api-gateway
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc | quote }}
---

apiVersion: v1
kind: Namespace
metadata:
  name: agents
  annotations:
    "helm.sh/resource-policy": keep
    "app.kubernetes.io/managed-by": "Helm"
    "config.linkerd.io/trace-collector": collector.linkerd-jaeger:55678 # or 14268?

---

apiVersion: v1
kind: Secret
metadata:
  name: rabbit
  namespace: agents
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc | quote }}
---

apiVersion: v1
kind: Namespace
metadata:
  name: thirdparties
  annotations:
    "helm.sh/resource-policy": keep
    "app.kubernetes.io/managed-by": "Helm"
    "config.linkerd.io/trace-collector": collector.linkerd-jaeger:55678 # or 14268?

---

apiVersion: v1
kind: Secret
metadata:
  name: rabbit
  namespace: thirdparties
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc | quote }}
---

apiVersion: v1
kind: Namespace
metadata:
  name: alpha
  annotations:
    "helm.sh/resource-policy": keep
    "app.kubernetes.io/managed-by": "Helm"
    "config.linkerd.io/trace-collector": collector.linkerd-jaeger:55678 # or 14268?

---

apiVersion: v1
kind: Secret
metadata:
  name: rabbit
  namespace: alpha
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc | quote }}
---

apiVersion: v1
kind: Namespace
metadata:
  name: enigma
  annotations:
    "helm.sh/resource-policy": keep
    "app.kubernetes.io/managed-by": "Helm"
    "config.linkerd.io/trace-collector": collector.linkerd-jaeger:55678 # or 14268?

---

apiVersion: v1
kind: Secret
metadata:
  name: rabbit
  namespace: enigma
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc | quote }}
---

apiVersion: v1
kind: Namespace
metadata:
  name: omnia
  annotations:
    "helm.sh/resource-policy": keep
    "app.kubernetes.io/managed-by": "Helm"
    "config.linkerd.io/trace-collector": collector.linkerd-jaeger:55678 # or 14268?

---

apiVersion: v1
kind: Secret
metadata:
  name: rabbit
  namespace: omnia
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc | quote }}
---

apiVersion: v1
kind: Namespace
metadata:
  name: scientia
  annotations:
    "helm.sh/resource-policy": keep
    "app.kubernetes.io/managed-by": "Helm"
    "config.linkerd.io/trace-collector": collector.linkerd-jaeger:55678 # or 14268?

---

apiVersion: v1
kind: Secret
metadata:
  name: rabbit
  namespace: scientia
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc | quote }}
---

apiVersion: v1
kind: Namespace
metadata:
  name: server
  annotations:
    "helm.sh/resource-policy": keep
    "app.kubernetes.io/managed-by": "Helm"
    "config.linkerd.io/trace-collector": collector.linkerd-jaeger:55678 # or 14268?

---

apiVersion: v1
kind: Secret
metadata:
  name: rabbit
  namespace: server
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc | quote }}
---

apiVersion: v1
kind: Namespace
metadata:
  name: clientone
  annotations:
    "helm.sh/resource-policy": keep
    "app.kubernetes.io/managed-by": "Helm"
    "config.linkerd.io/trace-collector": collector.linkerd-jaeger:55678 # or 14268?

---

apiVersion: v1
kind: Secret
metadata:
  name: rabbit
  namespace: clientone
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc | quote }}
---

apiVersion: v1
kind: Namespace
metadata:
  name: clienttwo
  annotations:
    "helm.sh/resource-policy": keep
    "app.kubernetes.io/managed-by": "Helm"
    "config.linkerd.io/trace-collector": collector.linkerd-jaeger:55678 # or 14268?

---

apiVersion: v1
kind: Secret
metadata:
  name: rabbit
  namespace: clienttwo
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc | quote }}
---

apiVersion: v1
kind: Namespace
metadata:
  name: clientthree
  annotations:
    "helm.sh/resource-policy": keep
    "app.kubernetes.io/managed-by": "Helm"
    "config.linkerd.io/trace-collector": collector.linkerd-jaeger:55678 # or 14268?

---

apiVersion: v1
kind: Secret
metadata:
  name: rabbit
  namespace: clientthree
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc | quote }}
