apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
        type: agent
      annotations:
        "linkerd.io/inject" : enabled
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: server
      # nodeName: server
      serviceAccountName: job-creator-server
      containers:
      - name: server
        image: {{ .Values.dockerArtifactAccount }}/agent:{{ .Values.branchNameTag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DATA_STEWARD_NAME
          value: server
        - name: OC_AGENT_HOST
          value: {{ .Values.tracingEndpoint }}
      - name: sidecar
        image: {{ .Values.dockerArtifactAccount }}/sidecar:{{ .Values.branchNameTag }}
        imagePullPolicy: Always
        env:
        - name: AMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbit
              key: password
        - name: AMQ_USER
          value: normal_user
        - name: OC_AGENT_HOST
          value: {{ .Values.tracingEndpoint }}

---

apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: server
spec:
  selector:
    app: server
    type: agent
  ports:
    - name: http-server-api
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server-ingress
  namespace: server
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: server.server.svc.cluster.local
    http:
      paths:
      - pathType: Prefix
        path: "/agent/v1/vflTrainRequest/server"
        backend:
          service:
            name: server
            port:
              number: 8080

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: server-pv
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
      # local path on node
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - server

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-pvc
  namespace: server
spec:
  volumeName: server-pv
  accessModes:
    - ReadWriteOnce   # Needed for multiple pods to mount simultaneously
  resources:
    requests:
      storage: 5Gi    # Adjust size as needed
  storageClassName: standard
